Ext.define("CueTrans.view.journey_management.JPSummary",{
	extend:"Ext.panel.Panel",
	height:200,
	baseCls:'c-search',
	layout:"column",
	initComponent: function()
	{
		var summCont=Ext.create("Ext.container.Container",{
			//baseCls:'c-search',
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			//width:100,
			columnWidth:.155,
			paging:10,
			defaults:{margin:10},
			items:
			[
				{
					xtype:"label",
					html:"Journey Plan Summary",
					//baseCls:'c-summ-hdrfont c-search'
					style:{
						"font-size":"1.7em"
					}
				}
			]
		})

		var openCont=Ext.create("Ext.container.Container",{
			//baseCls:'c-search',
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			//width:100,
			columnWidth:.155,
			paging:10,
			items:
			[
				{
					layout:"column",
					baseCls:'c-search',
					height:40,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Day",
							//baseCls:'c-search',
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"Open",
							//baseCls:'c-search',
							columnWidth:.3
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#F19252'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Current<br>Day",
							//baseCls:'c-summ-labelfont c-search',
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"20",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.3
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#b05315'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Upto<br>Previous<br>Day",
							//baseCls:'c-summ-labelfont c-summ-prevday',
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"25",
							//baseCls:'c-summ-bignumber c-summ-prevday',
							style:{
								"font-size":"2.5em"
							},																
							columnWidth:.3
						}							
					]
				}					
			]
		})
						
		var onTimeCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.115,
			items:
			[
				{
					layout:"fit",
					baseCls:'c-search',
					style:{
						background:'#157468'
					},					
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"OnTime",
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					defaults:{margin:10},
					style:{
						background:'#e97424'
					},
					height:80,
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"5",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"3",
							columnWidth:.3
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#d96010'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"10",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"6",
							columnWidth:.3
						}							
					]
				}					
			]
		})
				
		var delayCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.115,
			items:
			[
				{
					layout:"fit",
					baseCls:'c-search',
					style:{
						background:'#157468'
					},					
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"Delay",
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					defaults:{margin:10},
					style:{
						background:'#e2911b'
					},
					height:80,
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"12",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"4",
							columnWidth:.3
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#b07114'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"6",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"3",
							columnWidth:.3
						}							
					]
				}					
			]
		})
					
		var overdueCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.115,
			items:
			[
				{
					layout:"fit",
					baseCls:'c-search',
					style:{
						background:'#157468'
					},					
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"OverDue",
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					defaults:{margin:10},
					style:{
						background:'#f3a36d'
					},
					height:80,
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"1",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"0",
							columnWidth:.3
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#ed670e'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						{
							xtype:"label",
							html:"Running",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"1",
							columnWidth:.3
						},
						{
							xtype:"label",
							html:"Rest",
							columnWidth:.7
						},
						{
							xtype:"label",
							html:"1",
							columnWidth:.3
						}							
					]
				}					
			]
		})

		var lostCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.055,
			paging:10,
			items:
			[
				{
					layout:"fit",
					baseCls:'c-search',
					style:{
						background:'#b40303'
					},					
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"Lost",
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#e11a31'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"1",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.4
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#af1426'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"0",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							}
						}							
					]
				}
			]
		})
		
		var closedCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.145,
			paging:10,
			items:
			[
				{
					layout:"vbox",
					baseCls:'c-search',
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"Journey Plan Closed",							
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#13a857'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"1",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.4
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#108246'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"0",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.4
						}							
					]
				}
			]
		})
		

		var pendingCont=Ext.create("Ext.container.Container",{
			layout:
			{
				type:"vbox",
				align:"stretch"
			},
			height:200,
			columnWidth:.145,
			paging:10,
			items:
			[
				{
					layout:"vbox",
					baseCls:'c-search',
					height:40,
					items:
					[
						{
							xtype:"label",
							html:"Truck Release Pending",							
							margin:10
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#1388a9'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"1",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.4
						}							
					]
				},
				{
					layout:"column",
					baseCls:'c-search',
					style:{
						background:'#0e6882'
					},
					height:80,
					defaults:{margin:10},
					items:
					[
						/*
						{
							xtype:"label",
							html:"Lost",
							style:{
								"font-size":"2.0em"
							},								
							columnWidth:.6
						},
						*/
						{
							xtype:"label",
							html:"0",
							//baseCls:'c-search',
							style:{
								"font-size":"2.5em"
							},								
							columnWidth:.4
						}							
					]
				}
			]
		})
						
		this.callParent(arguments);
		
		this.add(summCont)
		this.add(openCont)
		this.add(onTimeCont)
		this.add(delayCont)
		this.add(overdueCont)
		
		this.add(lostCont)
		this.add(closedCont)
		this.add(pendingCont)
		
		
	}
})
